export enum MESSAGE_TYPES {
  SIGN_IN = 'SIGN_IN',
  NETWORK_CALL = 'NETWORK_CALL',
  REQUEST_USER = 'REQUEST_USER',
  SEND_USER = 'SEND_USER',
  SYNC_REQUESTS = 'SYNC_REQUESTS',
  REQUEST_USAGE = 'REQUEST_USAGE',
  REQUEST_CREDENTIALS = 'REQUEST_CREDENTIALS',
  SEND_CREDENTIALS = 'SEND_CREDENTIALS'
}
