export enum MESSAGE_TYPES {
  REQUEST_CREDENTIALS = 'REQUEST_CREDENTIALS',
  SEND_CREDENTIALS = 'SEND_CREDENTIALS',
  REQUEST_CONFIRMATION = 'REQUEST_CONFIRMATION',
  REQUEST_INITIAL_USAGE = 'REQUEST_INITIAL_USAGE',
  REQUEST_LISTEN_TO_USAGE = 'REQUEST_LISTEN_TO_USAGE',
  REQUEST_HOST_ALIAS_ARRAY = 'REQUEST_HOST_ALIAS_ARRAY'
}
