name: Deploy to App Engine on merge
'on':
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.19.0
      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: pnpm install
        run: pnpm install
      - uses: w9jds/firebase-action@master
        with:
          args: emulators:exec --only firestore,auth 'npx pnpm run test:ci'
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          FB_SA_KEY: ${{ secrets.FB_SA_KEY }}
          FIREBASE_apiKey: ${{ secrets.FIREBASE_APIKEY }}
          FIREBASE_authDomain: ${{ secrets.FIREBASE_AUTHDOMAIN }}
          FIREBASE_projectId: ${{ secrets.FIREBASE_PROJECTID }}
          FIREBASE_storageBucket: ${{ secrets.FIREBASE_STORAGEBUCKET }}
          FIREBASE_messagingSenderId: ${{ secrets.FIREBASE_MESSAGINGSENDERID }}
          FIREBASE_appId: ${{ secrets.FIREBASE_APPID }}
  build_and_deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.19.0
      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - id: generate_dotenv_file
        env:
          GEOLITE2_LICENSE_KEY: ${{ secrets.GEOLITE2_LICENSE_KEY }}
        working-directory: ./packages/data-analyzer
        run: echo "$GEOLITE2_LICENSE_KEY" > .env-for-app-yaml
      - id: prepare-app-yaml
        uses: mshick/fast-envsubst@v1
        with:
          env-file: packages/data-analyzer/.env-for-app-yaml
          in-file: packages/data-analyzer/app.yaml.template
          out-file: packages/data-analyzer/app.yaml
      - name: 'check env file'
        run: cat .env-for-app-yaml
        working-directory: ./packages/data-analyzer
      - name: pnpm install
        run: pnpm install
      - name: 'update IP database'
        working-directory: ./packages/data-analyzer
        env:
          GEOLITE2_LICENSE_KEY: ${{ secrets.GEOLITE2_LICENSE_KEY }}
        run: pnpm update-ip
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        env:
          GEOLITE2_LICENSE_KEY: ${{ secrets.GEOLITE2_LICENSE_KEY }}
        with:
          working_directory: ./packages/data-analyzer
          credentials: ${{ secrets.GCP_SA_KEY }}
